/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Challenge {
    stakeHH: number;
    taskId: bigint;
    timestamp: Time;
    challenger: Principal;
}
export type Time = bigint;
export interface Pledge {
    user: Principal;
    pledgedHH: number;
    projectId: bigint;
}
export interface Task {
    id: bigint;
    status: TaskStatus;
    assignee?: Principal;
    title: string;
    hhBudget: number;
    completionTime?: Time;
    description: string;
    projectId: bigint;
    dependencies: Array<bigint>;
    auditStartTime?: Time;
}
export interface PeerRating {
    projectId: bigint;
    timestamp: Time;
    rating: number;
    ratee: Principal;
    rater: Principal;
}
export interface Vote {
    weight: number;
    voteType: Variant_finalPrize_challenge_taskProposal;
    voter: Principal;
    timestamp: Time;
    targetId: bigint;
}
export interface UserProfile {
    totalPledgedHH: number;
    votingPower: number;
    friendlyUsername: string;
    squadRole: SquadRole;
    totalEarnedHH: number;
    profilePicture: string;
    overallReputationScore: number;
}
export interface Project {
    id: bigint;
    status: ProjectStatus;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    completionTime?: Time;
    totalPledgedHH: number;
    description: string;
    sharedResourceLink?: string;
    finalMonetaryValue: number;
    estimatedTotalHH: number;
}
export enum ProjectStatus {
    active = "active",
    completed = "completed",
    pledging = "pledging",
    archived = "archived"
}
export enum SquadRole {
    Journeyman = "Journeyman",
    Mentor = "Mentor",
    Apprentice = "Apprentice"
}
export enum TaskStatus {
    active = "active",
    completed = "completed",
    rejected = "rejected",
    proposed = "proposed",
    inAudit = "inAudit",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_finalPrize_challenge_taskProposal {
    finalPrize = "finalPrize",
    challenge = "challenge",
    taskProposal = "taskProposal"
}
export interface backendInterface {
    acceptTask(taskId: bigint): Promise<void>;
    approveTask(taskId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    challengeTask(taskId: bigint, stakeHH: number): Promise<void>;
    completeProject(projectId: bigint): Promise<void>;
    completeTask(taskId: bigint): Promise<void>;
    createProject(title: string, description: string, estimatedTotalHH: number, finalMonetaryValue: number, sharedResourceLink: string | null): Promise<bigint>;
    createTask(projectId: bigint, title: string, description: string, hhBudget: number, dependencies: Array<bigint>): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChallenges(taskId: bigint): Promise<Array<Challenge>>;
    getPeerRatings(projectId: bigint): Promise<Array<PeerRating>>;
    getPledges(projectId: bigint): Promise<Array<Pledge>>;
    getProjects(): Promise<Array<Project>>;
    getTasks(projectId: bigint): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVotes(targetId: bigint): Promise<Array<Vote>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    pledgeHH(projectId: bigint, pledgedHH: number): Promise<void>;
    ratePeer(ratee: Principal, projectId: bigint, rating: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    vote(targetId: bigint, voteType: Variant_finalPrize_challenge_taskProposal): Promise<void>;
}
import type { Project as _Project, ProjectStatus as _ProjectStatus, SquadRole as _SquadRole, Task as _Task, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Vote as _Vote } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTask(arg0);
            return result;
        }
    }
    async approveTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTask(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async challengeTask(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.challengeTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.challengeTask(arg0, arg1);
            return result;
        }
    }
    async completeProject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeProject(arg0);
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string, arg2: number, arg3: number, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2, arg3, to_candid_opt_n3(this.uploadFile, this.downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2, arg3, to_candid_opt_n3(this.uploadFile, this.downloadFile, arg4));
            return result;
        }
    }
    async createTask(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this.uploadFile, this.downloadFile, result);
        }
    }
    async getChallenges(arg0: bigint): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenges(arg0);
            return result;
        }
    }
    async getPeerRatings(arg0: bigint): Promise<Array<PeerRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeerRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeerRatings(arg0);
            return result;
        }
    }
    async getPledges(arg0: bigint): Promise<Array<Pledge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPledges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPledges(arg0);
            return result;
        }
    }
    async getProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(arg0);
                return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(arg0);
            return from_candid_vec_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getVotes(arg0: bigint): Promise<Array<Vote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVotes(arg0);
                return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVotes(arg0);
            return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async pledgeHH(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pledgeHH(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pledgeHH(arg0, arg1);
            return result;
        }
    }
    async ratePeer(arg0: Principal, arg1: bigint, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ratePeer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ratePeer(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async vote(arg0: bigint, arg1: Variant_finalPrize_challenge_taskProposal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.vote(arg0, to_candid_variant_n32(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vote(arg0, to_candid_variant_n32(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ProjectStatus_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n15(uploadFile, downloadFile, value);
}
function from_candid_Project_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n13(uploadFile, downloadFile, value);
}
function from_candid_SquadRole_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SquadRole): SquadRole {
    return from_candid_variant_n8(uploadFile, downloadFile, value);
}
function from_candid_TaskStatus_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n22(uploadFile, downloadFile, value);
}
function from_candid_Task_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n20(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n6(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(uploadFile, downloadFile, value);
}
function from_candid_Vote_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vote): Vote {
    return from_candid_record_n26(uploadFile, downloadFile, value);
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n5(uploadFile, downloadFile, value[0]);
}
function from_candid_record_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProjectStatus;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    completionTime: [] | [_Time];
    totalPledgedHH: number;
    description: string;
    sharedResourceLink: [] | [string];
    finalMonetaryValue: number;
    estimatedTotalHH: number;
}): {
    id: bigint;
    status: ProjectStatus;
    title: string;
    creator: Principal;
    participants: Array<Principal>;
    completionTime?: Time;
    totalPledgedHH: number;
    description: string;
    sharedResourceLink?: string;
    finalMonetaryValue: number;
    estimatedTotalHH: number;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n14(uploadFile, downloadFile, value.status),
        title: value.title,
        creator: value.creator,
        participants: value.participants,
        completionTime: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.completionTime)),
        totalPledgedHH: value.totalPledgedHH,
        description: value.description,
        sharedResourceLink: record_opt_to_undefined(from_candid_opt_n17(uploadFile, downloadFile, value.sharedResourceLink)),
        finalMonetaryValue: value.finalMonetaryValue,
        estimatedTotalHH: value.estimatedTotalHH
    };
}
function from_candid_record_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    assignee: [] | [Principal];
    title: string;
    hhBudget: number;
    completionTime: [] | [_Time];
    description: string;
    projectId: bigint;
    dependencies: Array<bigint>;
    auditStartTime: [] | [_Time];
}): {
    id: bigint;
    status: TaskStatus;
    assignee?: Principal;
    title: string;
    hhBudget: number;
    completionTime?: Time;
    description: string;
    projectId: bigint;
    dependencies: Array<bigint>;
    auditStartTime?: Time;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n21(uploadFile, downloadFile, value.status),
        assignee: record_opt_to_undefined(from_candid_opt_n23(uploadFile, downloadFile, value.assignee)),
        title: value.title,
        hhBudget: value.hhBudget,
        completionTime: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.completionTime)),
        description: value.description,
        projectId: value.projectId,
        dependencies: value.dependencies,
        auditStartTime: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.auditStartTime))
    };
}
function from_candid_record_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    voteType: {
        finalPrize: null;
    } | {
        challenge: null;
    } | {
        taskProposal: null;
    };
    voter: Principal;
    timestamp: _Time;
    targetId: bigint;
}): {
    weight: number;
    voteType: Variant_finalPrize_challenge_taskProposal;
    voter: Principal;
    timestamp: Time;
    targetId: bigint;
} {
    return {
        weight: value.weight,
        voteType: from_candid_variant_n27(uploadFile, downloadFile, value.voteType),
        voter: value.voter,
        timestamp: value.timestamp,
        targetId: value.targetId
    };
}
function from_candid_record_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalPledgedHH: number;
    votingPower: number;
    friendlyUsername: string;
    squadRole: _SquadRole;
    totalEarnedHH: number;
    profilePicture: string;
    overallReputationScore: number;
}): {
    totalPledgedHH: number;
    votingPower: number;
    friendlyUsername: string;
    squadRole: SquadRole;
    totalEarnedHH: number;
    profilePicture: string;
    overallReputationScore: number;
} {
    return {
        totalPledgedHH: value.totalPledgedHH,
        votingPower: value.votingPower,
        friendlyUsername: value.friendlyUsername,
        squadRole: from_candid_SquadRole_n7(uploadFile, downloadFile, value.squadRole),
        totalEarnedHH: value.totalEarnedHH,
        profilePicture: value.profilePicture,
        overallReputationScore: value.overallReputationScore
    };
}
function from_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    pledging: null;
} | {
    archived: null;
}): ProjectStatus {
    return "active" in value ? ProjectStatus.active : "completed" in value ? ProjectStatus.completed : "pledging" in value ? ProjectStatus.pledging : "archived" in value ? ProjectStatus.archived : value;
}
function from_candid_variant_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    proposed: null;
} | {
    inAudit: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "active" in value ? TaskStatus.active : "completed" in value ? TaskStatus.completed : "rejected" in value ? TaskStatus.rejected : "proposed" in value ? TaskStatus.proposed : "inAudit" in value ? TaskStatus.inAudit : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    finalPrize: null;
} | {
    challenge: null;
} | {
    taskProposal: null;
}): Variant_finalPrize_challenge_taskProposal {
    return "finalPrize" in value ? Variant_finalPrize_challenge_taskProposal.finalPrize : "challenge" in value ? Variant_finalPrize_challenge_taskProposal.challenge : "taskProposal" in value ? Variant_finalPrize_challenge_taskProposal.taskProposal : value;
}
function from_candid_variant_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Journeyman: null;
} | {
    Mentor: null;
} | {
    Apprentice: null;
}): SquadRole {
    return "Journeyman" in value ? SquadRole.Journeyman : "Mentor" in value ? SquadRole.Mentor : "Apprentice" in value ? SquadRole.Apprentice : value;
}
function from_candid_vec_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n12(uploadFile, downloadFile, x));
}
function from_candid_vec_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n19(uploadFile, downloadFile, x));
}
function from_candid_vec_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Vote>): Array<Vote> {
    return value.map((x)=>from_candid_Vote_n25(uploadFile, downloadFile, x));
}
function to_candid_SquadRole_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SquadRole): _SquadRole {
    return to_candid_variant_n31(uploadFile, downloadFile, value);
}
function to_candid_UserProfile_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalPledgedHH: number;
    votingPower: number;
    friendlyUsername: string;
    squadRole: SquadRole;
    totalEarnedHH: number;
    profilePicture: string;
    overallReputationScore: number;
}): {
    totalPledgedHH: number;
    votingPower: number;
    friendlyUsername: string;
    squadRole: _SquadRole;
    totalEarnedHH: number;
    profilePicture: string;
    overallReputationScore: number;
} {
    return {
        totalPledgedHH: value.totalPledgedHH,
        votingPower: value.votingPower,
        friendlyUsername: value.friendlyUsername,
        squadRole: to_candid_SquadRole_n30(uploadFile, downloadFile, value.squadRole),
        totalEarnedHH: value.totalEarnedHH,
        profilePicture: value.profilePicture,
        overallReputationScore: value.overallReputationScore
    };
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SquadRole): {
    Journeyman: null;
} | {
    Mentor: null;
} | {
    Apprentice: null;
} {
    return value == SquadRole.Journeyman ? {
        Journeyman: null
    } : value == SquadRole.Mentor ? {
        Mentor: null
    } : value == SquadRole.Apprentice ? {
        Apprentice: null
    } : value;
}
function to_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_finalPrize_challenge_taskProposal): {
    finalPrize: null;
} | {
    challenge: null;
} | {
    taskProposal: null;
} {
    return value == Variant_finalPrize_challenge_taskProposal.finalPrize ? {
        finalPrize: null
    } : value == Variant_finalPrize_challenge_taskProposal.challenge ? {
        challenge: null
    } : value == Variant_finalPrize_challenge_taskProposal.taskProposal ? {
        taskProposal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
