/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challenge {
  'stakeHH' : number,
  'taskId' : bigint,
  'timestamp' : Time,
  'challenger' : Principal,
}
export interface PeerRating {
  'projectId' : bigint,
  'timestamp' : Time,
  'rating' : number,
  'ratee' : Principal,
  'rater' : Principal,
}
export interface Pledge {
  'user' : Principal,
  'pledgedHH' : number,
  'projectId' : bigint,
}
export interface Project {
  'id' : bigint,
  'status' : ProjectStatus,
  'title' : string,
  'creator' : Principal,
  'participants' : Array<Principal>,
  'completionTime' : [] | [Time],
  'totalPledgedHH' : number,
  'description' : string,
  'sharedResourceLink' : [] | [string],
  'finalMonetaryValue' : number,
  'estimatedTotalHH' : number,
}
export type ProjectStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'pledging' : null } |
  { 'archived' : null };
export type SquadRole = { 'Journeyman' : null } |
  { 'Mentor' : null } |
  { 'Apprentice' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : [] | [Principal],
  'title' : string,
  'hhBudget' : number,
  'completionTime' : [] | [Time],
  'description' : string,
  'projectId' : bigint,
  'dependencies' : Array<bigint>,
  'auditStartTime' : [] | [Time],
}
export type TaskStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'proposed' : null } |
  { 'inAudit' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'totalPledgedHH' : number,
  'votingPower' : number,
  'friendlyUsername' : string,
  'squadRole' : SquadRole,
  'totalEarnedHH' : number,
  'profilePicture' : string,
  'overallReputationScore' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vote {
  'weight' : number,
  'voteType' : { 'finalPrize' : null } |
    { 'challenge' : null } |
    { 'taskProposal' : null },
  'voter' : Principal,
  'timestamp' : Time,
  'targetId' : bigint,
}
export interface _SERVICE {
  'acceptTask' : ActorMethod<[bigint], undefined>,
  'approveTask' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'challengeTask' : ActorMethod<[bigint, number], undefined>,
  'completeProject' : ActorMethod<[bigint], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'createProject' : ActorMethod<
    [string, string, number, number, [] | [string]],
    bigint
  >,
  'createTask' : ActorMethod<
    [bigint, string, string, number, Array<bigint>],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallenges' : ActorMethod<[bigint], Array<Challenge>>,
  'getPeerRatings' : ActorMethod<[bigint], Array<PeerRating>>,
  'getPledges' : ActorMethod<[bigint], Array<Pledge>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getTasks' : ActorMethod<[bigint], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVotes' : ActorMethod<[bigint], Array<Vote>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pledgeHH' : ActorMethod<[bigint, number], undefined>,
  'ratePeer' : ActorMethod<[Principal, bigint, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'vote' : ActorMethod<
    [
      bigint,
      { 'finalPrize' : null } |
        { 'challenge' : null } |
        { 'taskProposal' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];