/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SquadRole = IDL.Variant({
  'Journeyman' : IDL.Null,
  'Mentor' : IDL.Null,
  'Apprentice' : IDL.Null,
  'Masters' : IDL.Null,
});
export const ParticipationLevel = IDL.Variant({
  'Journeyman' : IDL.Null,
  'GuestArtist' : IDL.Null,
  'Apprentice' : IDL.Null,
  'Master' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'totalPledgedHH' : IDL.Float64,
  'votingPower' : IDL.Float64,
  'friendlyUsername' : IDL.Text,
  'efficiencyBadgesCount' : IDL.Nat,
  'squadRole' : SquadRole,
  'constructivenessRating' : IDL.Float64,
  'totalEnablerPoints' : IDL.Nat,
  'totalEarnedHH' : IDL.Float64,
  'profilePicture' : IDL.Text,
  'overallReputationScore' : IDL.Float64,
  'participationLevel' : ParticipationLevel,
  'participationLevelLocked' : IDL.Bool,
});
export const Time = IDL.Int;
export const Challenge = IDL.Record({
  'stakeHH' : IDL.Float64,
  'taskId' : IDL.Nat,
  'timestamp' : Time,
  'challenger' : IDL.Principal,
});
export const PeerRating = IDL.Record({
  'projectId' : IDL.Nat,
  'timestamp' : Time,
  'rating' : IDL.Float64,
  'ratee' : IDL.Principal,
  'rater' : IDL.Principal,
});
export const PledgeStatus = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'confirmed' : IDL.Null,
  'reassigned' : IDL.Null,
});
export const PledgeTarget = IDL.Variant({
  'task' : IDL.Nat,
  'otherTasks' : IDL.Null,
});
export const Pledge = IDL.Record({
  'status' : PledgeStatus,
  'user' : IDL.Principal,
  'target' : PledgeTarget,
  'projectId' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const ProjectStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'pledging' : IDL.Null,
  'archived' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'participants' : IDL.Vec(IDL.Principal),
  'completionTime' : IDL.Opt(Time),
  'totalPledgedHH' : IDL.Float64,
  'description' : IDL.Text,
  'sharedResourceLink' : IDL.Opt(IDL.Text),
  'finalMonetaryValue' : IDL.Float64,
  'estimatedTotalHH' : IDL.Float64,
});
export const TaskStatus = IDL.Variant({
  'active' : IDL.Null,
  'taskConfirmed' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'proposed' : IDL.Null,
  'inAudit' : IDL.Null,
  'pendingConfirmation' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'assignee' : IDL.Opt(IDL.Principal),
  'title' : IDL.Text,
  'hhBudget' : IDL.Float64,
  'completionTime' : IDL.Opt(Time),
  'description' : IDL.Text,
  'projectId' : IDL.Nat,
  'dependencies' : IDL.Vec(IDL.Nat),
  'auditStartTime' : IDL.Opt(Time),
});
export const Vote = IDL.Record({
  'weight' : IDL.Float64,
  'voteType' : IDL.Variant({
    'finalPrize' : IDL.Null,
    'challenge' : IDL.Null,
    'taskProposal' : IDL.Null,
  }),
  'voter' : IDL.Principal,
  'timestamp' : Time,
  'targetId' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  'acceptTask' : IDL.Func([IDL.Nat], [], []),
  'approveTask' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'challengeTask' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'checkAndExpireOldPledges' : IDL.Func([], [], []),
  'completeProject' : IDL.Func([IDL.Nat], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'confirmPledge' : IDL.Func([IDL.Nat], [], []),
  'confirmTask' : IDL.Func([IDL.Nat], [], []),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallenges' : IDL.Func([IDL.Nat], [IDL.Vec(Challenge)], ['query']),
  'getCurrentUserStatus' : IDL.Func(
      [],
      [
        IDL.Variant({
          'unapproved' : IDL.Null,
          'admin' : IDL.Null,
          'pending' : IDL.Null,
          'approved' : IDL.Null,
        }),
      ],
      ['query'],
    ),
  'getPeerRatings' : IDL.Func([IDL.Nat], [IDL.Vec(PeerRating)], ['query']),
  'getPledges' : IDL.Func([IDL.Nat], [IDL.Vec(Pledge)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVotes' : IDL.Func([IDL.Nat], [IDL.Vec(Vote)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'pledgeToTask' : IDL.Func([IDL.Nat, PledgeTarget, IDL.Float64], [], []),
  'ratePeer' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Float64], [], []),
  'reassignFromOtherTasks' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, SquadRole, ParticipationLevel], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setParticipationLevel' : IDL.Func([ParticipationLevel], [], []),
  'updateParticipationLevel' : IDL.Func(
      [IDL.Principal, ParticipationLevel],
      [],
      [],
    ),
  'vote' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'finalPrize' : IDL.Null,
          'challenge' : IDL.Null,
          'taskProposal' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SquadRole = IDL.Variant({
    'Journeyman' : IDL.Null,
    'Mentor' : IDL.Null,
    'Apprentice' : IDL.Null,
    'Masters' : IDL.Null,
  });
  const ParticipationLevel = IDL.Variant({
    'Journeyman' : IDL.Null,
    'GuestArtist' : IDL.Null,
    'Apprentice' : IDL.Null,
    'Master' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'totalPledgedHH' : IDL.Float64,
    'votingPower' : IDL.Float64,
    'friendlyUsername' : IDL.Text,
    'efficiencyBadgesCount' : IDL.Nat,
    'squadRole' : SquadRole,
    'constructivenessRating' : IDL.Float64,
    'totalEnablerPoints' : IDL.Nat,
    'totalEarnedHH' : IDL.Float64,
    'profilePicture' : IDL.Text,
    'overallReputationScore' : IDL.Float64,
    'participationLevel' : ParticipationLevel,
    'participationLevelLocked' : IDL.Bool,
  });
  const Time = IDL.Int;
  const Challenge = IDL.Record({
    'stakeHH' : IDL.Float64,
    'taskId' : IDL.Nat,
    'timestamp' : Time,
    'challenger' : IDL.Principal,
  });
  const PeerRating = IDL.Record({
    'projectId' : IDL.Nat,
    'timestamp' : Time,
    'rating' : IDL.Float64,
    'ratee' : IDL.Principal,
    'rater' : IDL.Principal,
  });
  const PledgeStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'confirmed' : IDL.Null,
    'reassigned' : IDL.Null,
  });
  const PledgeTarget = IDL.Variant({
    'task' : IDL.Nat,
    'otherTasks' : IDL.Null,
  });
  const Pledge = IDL.Record({
    'status' : PledgeStatus,
    'user' : IDL.Principal,
    'target' : PledgeTarget,
    'projectId' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const ProjectStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'pledging' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'participants' : IDL.Vec(IDL.Principal),
    'completionTime' : IDL.Opt(Time),
    'totalPledgedHH' : IDL.Float64,
    'description' : IDL.Text,
    'sharedResourceLink' : IDL.Opt(IDL.Text),
    'finalMonetaryValue' : IDL.Float64,
    'estimatedTotalHH' : IDL.Float64,
  });
  const TaskStatus = IDL.Variant({
    'active' : IDL.Null,
    'taskConfirmed' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'proposed' : IDL.Null,
    'inAudit' : IDL.Null,
    'pendingConfirmation' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'assignee' : IDL.Opt(IDL.Principal),
    'title' : IDL.Text,
    'hhBudget' : IDL.Float64,
    'completionTime' : IDL.Opt(Time),
    'description' : IDL.Text,
    'projectId' : IDL.Nat,
    'dependencies' : IDL.Vec(IDL.Nat),
    'auditStartTime' : IDL.Opt(Time),
  });
  const Vote = IDL.Record({
    'weight' : IDL.Float64,
    'voteType' : IDL.Variant({
      'finalPrize' : IDL.Null,
      'challenge' : IDL.Null,
      'taskProposal' : IDL.Null,
    }),
    'voter' : IDL.Principal,
    'timestamp' : Time,
    'targetId' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    'acceptTask' : IDL.Func([IDL.Nat], [], []),
    'approveTask' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'challengeTask' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'checkAndExpireOldPledges' : IDL.Func([], [], []),
    'completeProject' : IDL.Func([IDL.Nat], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'confirmPledge' : IDL.Func([IDL.Nat], [], []),
    'confirmTask' : IDL.Func([IDL.Nat], [], []),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallenges' : IDL.Func([IDL.Nat], [IDL.Vec(Challenge)], ['query']),
    'getCurrentUserStatus' : IDL.Func(
        [],
        [
          IDL.Variant({
            'unapproved' : IDL.Null,
            'admin' : IDL.Null,
            'pending' : IDL.Null,
            'approved' : IDL.Null,
          }),
        ],
        ['query'],
      ),
    'getPeerRatings' : IDL.Func([IDL.Nat], [IDL.Vec(PeerRating)], ['query']),
    'getPledges' : IDL.Func([IDL.Nat], [IDL.Vec(Pledge)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVotes' : IDL.Func([IDL.Nat], [IDL.Vec(Vote)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'pledgeToTask' : IDL.Func([IDL.Nat, PledgeTarget, IDL.Float64], [], []),
    'ratePeer' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Float64], [], []),
    'reassignFromOtherTasks' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, SquadRole, ParticipationLevel],
        [],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setParticipationLevel' : IDL.Func([ParticipationLevel], [], []),
    'updateParticipationLevel' : IDL.Func(
        [IDL.Principal, ParticipationLevel],
        [],
        [],
      ),
    'vote' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'finalPrize' : IDL.Null,
            'challenge' : IDL.Null,
            'taskProposal' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };